server:
  servlet:
    context-path: /seller
  port: 8082


rpc:
  client:
    url:  http://localhost:8081/manager
#rpc.manager.url: http:localhost:8081/manager/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fpsystem_seller?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19980808
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss.SSS
#    time-zone: GMT+8


#  jpa:
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#    show-sql: true





