spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/fpsystem_manager?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19980808

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
server:
  servlet:
    context-path: /manager
  port: 8081

logging:
  level:
    com.googlecode.jsonrpc4j: debug
